---
title: "NBA"
author: "Alessia Petracin"
date: "2024-02-03"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
players <- read.csv("/Users/alessia/Desktop/Statistics/nba.csv")
summary(players)
# check for missing data
sum(is.na(players))
```
Check skewness of the data
```{r}
# Empirical skewness (b1)
library(moments)
cols <- colnames(players[c(8:20)])
for (i in seq(1:13)){
x <- players[(cols[i])]
b1.x <- skewness(x)
print(b1.x)
if (b1.x > 0){
  print('Positively skewed - right-tailed')
} else {
  print('Negatively skewed - left-tailed')
}
}
```

```{r}
# Quartile skewness
x <- 1
while (x < 14){
for (i in players[8:20]){
sum.x <- summary(i)
qs.x <- ((sum.x[5] - sum.x[3]) - (sum.x[3] - sum.x[2]))/(sum.x[5] - sum.x[2])
print(cols[x])
print(qs.x)
if (qs.x > 0){
  print('Positively skewed - right-tailed')
} else {
  print('Negatively skewed - left-tailed')
}
x <- x + 1
}
}
```

```{r}
# MC (medcouple) - robust to outliers
library(robustbase)
x <- 1
while (x < 14){
for (i in players[8:20]){
x.mc <- mc(i)
print(cols[x])
print(x.mc)
if (x.mc > 0){
  print('Positively skewed - right-tailed')
} 
else if (x.mc == 0) {
  print('Not skewed')
}
else if (x.mc < 0) {
  print('Negatively skewed - left-tailed')
}
x <- x + 1
}
}
```



